name: Test and Deploy Pages

on:
  push:
    branches:
    - master

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
        npm run test
      env:
        CI: true

  build-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2

    - name: Build 
      run: npm install && npm run-script build

    - run: mv $GITHUB_WORKSPACE/build/config/config-override-demo.json $GITHUB_WORKSPACE/build/config/config-override.json
      shell: bash

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build